config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :applications
  root :to => 'home#index'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application.rb
class Application < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
  devise :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.where(user_id: current_user)
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @application.user_id = current_user.id
    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:link, :due, :num_recommendations, :essay, :essay_topics, :award_amount, :essay_word_count)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern
 
	def set_header
      		response.headers["Content-Type"] = "text/xml"
	end
 
	def render_twiml(response)
      		render text: response.text
	end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_home, only: [:show]

  # GET /home
  # GET /home.json
  def index
 
  end

  # GET /home/1
  # GET /home/1.json
  def show
  end

  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'
 
class SendTextController < ApplicationController
  def index
  end

  def send_text_message
    number_to_send_to = params[:number_to_send_to]

    twilio_sid = AC8462b3cfad999c1b46f67da5ee678565
    twilio_token = 1f027275e60dd7138d8a24bec34645db
    twilio_phone_number = "7043127378"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => +1#{7043127378}",
      :to => number_to_send_to,
      :body => "Welcome to app.ly! Let's get started. Reply APPLY to verify your phone number."
    ) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/Home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Welcome to app.ly!</h1>
<% if user_signed_in? %>
  <li><%= link_to('View Saved Applications or Enter a New Application', applications_path) %> <br>
  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
  <!--<%= link_to('Enter A New Application', new_application_path) %> -->      
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<p>App.ly is a tool to help you manage your applications.</p> 

<p>Applying for colleges? Jobs? Scholarships? Internships? We've got you covered.</p> 

<p>Never miss an application deadline again.</p> 

<p>Here's how it works:</p>

<p>YOU choose the type of opportunity you're applying for (e.g. college, job, scholarship, internship, or other) and fill out our customized form with all the particulars including the link to the application's website, it's due date, and the number of recommendations needed. You can add additional information to the form and fill in as little or as much as you wish!</p>

<p>WE send you SMS (text message) reminders to your mobile device letting you know you have an application due. You choose to receive reminders 1 month, 2 weeks, 1 week, and/or 1 day prior to the application's deadline.</p>

<p>Log-in to app.ly on your desktop or mobile device to view all your saved application due dates and information.</p>

<p>Why app.ly? Simple. Success occurs when opportunity meets preparation. Let us handle the prep work and as for you? Go get em' kid.</p> 

app/views/applications/_form.html.erb
<%= form_for(application) do |f| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2>Uh-oh! We found <%= pluralize(application.errors.count, "error") %>. Give it another try.</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :category %>
    <%= f.select :category_id, [['College', 1],['Scholarship',2], ['Job',3], ['Internship',4], ['Summer Program',5], ['Leadership Position',6], ['Other',7]]%> <!--options_from_collection_for_select(Category.all, "id", "name") %>-->
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :due %>
    <%= f.datetime_select :due %>
  </div>

  <div class="field">
    <%= f.label 'Number of recommendations' %>
    <%= f.number_field :num_recommendations %>
  </div>

  <div class="field">
    <%= f.label :essay %>
    <%= f.check_box :essay %>
  </div>

  <div class="field">
    <%= f.label :essay_topics %>
    <%= f.text_area :essay_topics %>
  </div>

  <div class="field">
    <%= f.label :award_amount %> <span>$<span>
    <%= f.number_field :award_amount %>
  </div>

  <div class="field">
    <%= f.label :essay_word_count %>
    <%= f.number_field :essay_word_count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>
<li><%= link_to('Enter A New Application', new_application_path) %> <br>
<li><%= link_to('Return To Home', root_path) %> <br>
<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> <br>
<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Deadline</th>
      <th># of Recommendations</th>
      <th>Essay</th>
      <th>Essay topics</th>
      <th>Award Amount ($)</th>
      <th>Essay Word Count</th>
      <th colspan="3"></th>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.link %></td>
        <td><%= application.due %></td>
        <td><%= application.num_recommendations %></td>
        <td><%= application.essay %></td>
        <td><%= application.essay_topics %></td>
        <td><%= application.award_amount %></td>
        <td><%= application.essay_word_count %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Delete', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/applications/new.html.erb
<h3>New Application</h3>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @application.link %>
</p>

<p>
  <strong>Due:</strong>
  <%= @application.due %>
</p>
<p>
  <strong>Number of recommendations:</strong>
  <%= @application.num_recommendations %>
</p>

<p>
  <strong>Essay:</strong>
  <%= @application.essay %>
</p>

<p>
  <strong>Essay topics:</strong>
  <%= @application.essay_topics %>
</p>

<p>
  <strong>Award amount:</strong>
  <%= @application.award_amount %>
</p>

<p>
  <strong>Essay word count:</strong>
  <%= @application.essay_word_count %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2>Whoops! We found <%= pluralize(application.errors.count, "error") %>. Give it another try.</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>app.ly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
  <%= link_to applications_path do %>
  <!-- <h1>App.ly</h1> -->
  <% end %>
 <!--  <%= link_to 'New Application', new_application_path %>
  <%= link_to 'New Applicatons Category', new_category_path %> -->
  <br>
 



    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>